<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.1 (Python 3.8.1 on win32)" generated="20200718 14:22:43.502" rpa="false">
<suite id="s1" name="Suites">
<suite id="s1-s1" name="Sim" source="C:\Automation\AppiumLibraryRobotFramework\TestCases\Sim.robot">
<test id="s1-s1-t1" name="Open the Application">
<kw name="Open Application" library="AppiumLibrary">
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |</doc>
<arguments>
<arg>remote_url=http://localhost:4723/wd/hub</arg>
<arg>device=R38MC00R9KJ</arg>
<arg>platformName=Android</arg>
<arg>deviceName=AndroidDevice</arg>
<arg>automationName=uiautomator2</arg>
<arg>app=C:\\Automation\\AppiumLibraryRobotFramework\\TestCases\\..\\App\\DemoApp.apk</arg>
</arguments>
<msg timestamp="20200718 14:22:46.446" level="INFO">Could not connect to port 4723 on host localhost</msg>
<msg timestamp="20200718 14:22:46.446" level="INFO">Could not get IP address for host: localhost</msg>
<msg timestamp="20200718 14:22:48.457" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x03F20370&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20200718 14:22:50.478" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x03F203E8&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20200718 14:22:52.494" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x03F20418&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20200718 14:22:54.577" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20200718 14:22:54.504" endtime="20200718 14:22:54.578"></status>
</kw>
<msg timestamp="20200718 14:22:54.579" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20200718 14:22:54.682" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x03F204C0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</msg>
<status status="FAIL" starttime="20200718 14:22:44.418" endtime="20200718 14:22:54.682"></status>
</kw>
<status status="FAIL" starttime="20200718 14:22:44.416" endtime="20200718 14:22:54.683" critical="yes">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x03F204C0&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</status>
</test>
<status status="FAIL" starttime="20200718 14:22:43.609" endtime="20200718 14:22:54.684"></status>
</suite>
<status status="FAIL" starttime="20200718 14:22:43.505" endtime="20200718 14:22:54.686"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Suites">Suites</stat>
<stat pass="0" fail="1" id="s1-s1" name="Sim">Suites.Sim</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200718 14:22:48.457" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x03F20370&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20200718 14:22:50.478" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x03F203E8&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20200718 14:22:52.494" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x03F20418&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg timestamp="20200718 14:22:54.579" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
